#ifndef __IOTEX_PAL_DEVICE_REGISTER_CONFIG__
#define __IOTEX_PAL_DEVICE_REGISTER_CONFIG__

#include <stdint.h>

#define IOTEX_PAL_DEVICE_REGISTER_MODE_SERIAL       0x00
#define IOTEX_PAL_DEVICE_REGISTER_MODE_HTTPS        0x01

#define IOTEX_PAL_DEVICE_REGISTER_MODE              IOTEX_PAL_DEVICE_REGISTER_MODE_SERIAL

#define IOTEX_PAL_DEVICE_REGISTER_COMMAND_DID_UPLOAD            'H'
#define IOTEX_PAL_DEVICE_REGISTER_COMMAND_DIDDOC_UPLOAD         'B'
#define IOTEX_PAL_DEVICE_REGISTER_COMMAND_SIGNATURE_RESPONSE    'S'


#endif